name: encriptation
description: Siganture generation tool for PayU API integration.
version: 0.0.1
# homepage:  https://github.com/luisfelipesantofimio/payu-signature-generation

environment:
  sdk: '>=2.18.2 <3.0.0'

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
dependencies:
  crypto: ^3.0.2
